apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mongodb
    tier: database
spec:
  clusterIP: None
  selector: 
    project: roboshop
    environment: dev
    component: mongodb
    tier: database
  ports: 
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

